name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-demo:latest
            ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-demo:${{ github.sha }}

  deploy_local:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Local PC
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.LOCAL_DEPLOY_HOST }}
          username: ${{ secrets.LOCAL_DEPLOY_USER }}
          key: ${{ secrets.LOCAL_DEPLOY_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-demo:latest
            docker stop nodejs-devops-demo || true
            docker rm nodejs-devops-demo || true
            docker run -d -p 3000:3000 \
              --restart always \
              --name nodejs-devops-demo \
              ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-demo:latest

  # deploy_remote:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to Remote Server
  #       uses: appleboy/ssh-action@v0.1.8
  #       with:
  #         host: ${{ secrets.DEPLOY_HOST }}
  #         username: ${{ secrets.DEPLOY_USER }}
  #         key: ${{ secrets.DEPLOY_KEY }}
  #         script: |
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-demo:latest
  #           docker stop nodejs-devops-demo || true
  #           docker rm nodejs-devops-demo || true
  #           docker run -d -p 3000:3000 --name nodejs-devops-demo ${{ secrets.DOCKER_USERNAME }}/nodejs-devops-demo:latest
